import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import Header from "../../components/Header/Header";
import styles from "../../styles/Home.module.css";
import download from "../../public/Static/images/download.png";
import { fetchCategoryJoke, getCategories } from "../fetch";

export default function Categories(props: any) {
  const [selectedCategory, setSelectedCategory] = useState<string>("");
  const [selectedJoke, setSelectedJoke] = useState<any>({});

  useEffect(() => {
    const currentJokeFunction = async () => {
      const currentJoke = await fetchCategoryJoke(selectedCategory);
      setSelectedJoke(currentJoke);
    };
    currentJokeFunction();
  }, [selectedCategory]);

  return (
    <>
      <Head>
        <title>Categories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Static/images/chucky2.png" />
      </Head>

      <main className={styles.categoriespage}>
        <header className={styles.header}>
          {" "}
          <Image className={styles.logo} alt="logo" src={download}></Image>
          <div>
            <Link href="/">
              <button className={styles.button} type="button">
                Home Page
              </button>
            </Link>
            <Link href="/Search">
              <button className={styles.button} type="button">
                Search
              </button>
            </Link>
          </div>
        </header>
        <h3 className={styles.title}>Categories</h3>

        <div className={styles.showCategoryDiv}>
          <h4><span style={{marginRight:'10px;'}}>&#9733;</span>Selected Category: {selectedCategory} </h4>
          <h4><span style={{marginRight:'10px;'}} >&#9733;</span>Selected Joke: {selectedJoke.value}</h4>
          </div>
       
        <div className={styles.categoriesParentDiv}>
          {props.categories.map((category: string, index: number) => {
            return (
              <div
                onClick={() => setSelectedCategory(category)}
                className={styles.categoriesDiv}
                key={index}
              >
                {category}
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const categories = await getCategories();
  return {
    props: { categories },
  };
}
