import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ReactNode, use, useEffect, useState } from "react";
import Header from "../../components/Header/Header";
import styles from "../../styles/Home.module.css";
import download from "../../public/Static/images/download.png";
import { fetchCurrentWord } from "../fetch";

export default function SearchPage(props: any) {
  const [currentUserSearch, setCurrentUserSearch] = useState<string>("");
  const [clicked, setClicked] = useState<boolean>(false);
  const [resultsObject, setResultsObject] = useState<any>(null);

  useEffect(() => {
    // Do not proceed if clicked is not true
    if (clicked === false) return;

    // Do not proceed if user hasn't given a keyword
    if (currentUserSearch === "") return;

    // Fetching data via the API
    const fetchUserSearch = async () => {
      const userSearch = await fetchCurrentWord(currentUserSearch);
      // Update State
      setResultsObject(userSearch);

      // Reverting set clicked state
     
    };

    // Invoke the async fetch data function
   
    fetchUserSearch();
    setClicked(false);
  }, [clicked]);

  const ResultsObjects = () => {
    if (
      clicked === true &&
      resultsObject !== null &&
      currentUserSearch.length > 0
    ) {
      return (
        <div className={styles.jokediv}>
          <ul>
            {resultsObject?.result?.map((joke: any, index: number) => {
              return <li key={index}>{joke?.value}</li>;
            })}
          </ul>
        </div>
      );
    } else if (
      clicked === true &&
      currentUserSearch.length > 0 &&
      resultsObject === null
    ) {
      console.log("no such keyword");
      return (
        <div className={styles.nojoke}>
          "There is no joke with this keyword!"
        </div>
      );
    } else if (clicked === true  && currentUserSearch.length === 0 &&
      resultsObject === null ) {
      console.log("no word entry from user");
      return <div className={styles.noWordGiven}>Please type a keyword!</div>;
    }
    else { return;}
  };

  return (
    <div>
      <Head>
        <title>Search Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Static/images/chucky2.png" />
      </Head>
      <main className={styles.searchpage}>
        <header className={styles.header}>
          {" "}
          <Image className={styles.logo} alt="logo" src={download}></Image>
          <div>
            <Link href="/">
              <button className={styles.button} type="button">
                Home Page
              </button>
            </Link>
            <Link href="/Categories">
              <button className={styles.button} type="button">
                Categories
              </button>
            </Link>
          </div>
        </header>
        <div style={{ flexDirection: "row" }}>
          <h3 className={styles.title}>Search Page</h3>
          <h3 style={{ textAlign: "center" }}>
            Use a keyword to find the joke you are looking for!
          </h3>
          <div className={styles.formdiv} style={{ width: "100%" }}>
            <div className={styles.searchform}>
              <input
                type="text"
                className={styles.searchforminput}
                onChange={(event) => setCurrentUserSearch(event.target.value)}
              />
              <button
                className={styles.searchformbutton}
                onClick={() => setClicked(true)}
              >
                <i className="fa fa-search"></i>Search Joke
              </button>
            </div>
            {/* {clicked === true && currentUserSearch !== "" ? (
              <div className={styles.secondDiv}> */}
                <ResultsObjects />
              {/* </div>
            ) : null} */}
          </div>
        </div>
      </main>
    </div>
  );
}
