import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import download from "../public/Static/images/download.png";
import chucky from "../public/Static/images/chucky2.png";
import Header from "../components/Header/Header";
import Link from "next/link";
import {fetchJoke} from "./fetch";

export default function Home(props: any) {
  const [isShown, setIsShown] = useState(false);
  const [currentJoke, setCurrentJoke] = useState(Object);

  useEffect(() => {
    const updateJoke = async () => {
      const joke = await fetchJoke();
      setCurrentJoke(joke);
    };
    updateJoke();
  }, [isShown]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to Chuck Noris Jokes Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="Static/images/chucky2.png" />
      </Head>

      <main className={styles.main}>
        <Header></Header>
        <div className={styles.firstsection}>
          <h3 className={styles.title}>Welcome to Chuckiverse</h3>
          <button
            className={styles.hoverme}
            type="button"
            onMouseEnter={() => setIsShown(true)}
            onMouseLeave={() => setIsShown(false)}
          >
            Hover Me
          </button>
          <div className={styles.randomjoke}>
            <blockquote className={styles.blockquote}>
              Chuck Norris Joke: "{currentJoke?.value}"
            </blockquote>
          </div>
        </div>
        <div className="styles.categoriesDiv"></div>
      </main>
      <div className={styles.lastdiv}>
        <Image className={styles.chuckImage} alt="logo" src={chucky}></Image>
        <div></div>
      </div>
      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
}
